name: Deploy PWA to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Secret API URL
        # This searches your app.js file for the placeholder and replaces it with the secret
        run: |
          sed -i 's|YOUR_SECRET_API_URL_HERE|${{ secrets.GAS_API_URL }}|g' config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./